import { mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import type { BookIndexV2, ChronicleEntry, TopicEntry, CardEntry } from "./book-index-v2.js";

export interface CatalogResult {
  /** Repo-rooted paths regenerated by this run. Caller stages via `git add`. */
  written: string[];
}

/**
 * Regenerate the user-facing catalog files from BookIndexV2:
 *
 *   book/index.md            — front page; one section per project, with
 *                              recent chronicles + topic list + card type
 *                              breakdown. Catalog (curated bullets), not a flat TOC.
 *   book/_meta/timeline.md   — global newest-first timeline of every chronicle
 *                              + every card update across all projects.
 *   book/<project>/index.md  — per-project landing page, lists its
 *                              chronicles / topics / cards in three sections.
 *
 * Pure string concatenation; deterministic; no LLM. Re-run is idempotent.
 */
export function generateBookCatalog(repoRoot: string, idx: BookIndexV2): CatalogResult {
  const written: string[] = [];

  // Bucket entries by project.
  const chroniclesByProject = bucketBy(Object.values(idx.chronicles), (c) => c.project);
  const topicsByProject = bucketBy(Object.values(idx.topics), (t) => t.project);
  const cardsByProject = bucketBy(Object.values(idx.cards), (c) => c.project);

  // Project list = union of all projects appearing anywhere, sorted, with
  // _global pulled to the end so it doesn't dominate the top of the catalog.
  const projectSet = new Set<string>();
  for (const p of chroniclesByProject.keys()) projectSet.add(p);
  for (const p of topicsByProject.keys()) projectSet.add(p);
  for (const p of cardsByProject.keys()) projectSet.add(p);
  const projects = [...projectSet].sort((a, b) => {
    if (a === "_global") return 1;
    if (b === "_global") return -1;
    return a.localeCompare(b);
  });

  // Front page.
  const frontPath = "book/index.md";
  writeRel(repoRoot, frontPath, renderFront({
    projects,
    chroniclesByProject,
    topicsByProject,
    cardsByProject,
    latestUpdate: latestUpdate(idx),
  }));
  written.push(frontPath);

  // Global timeline.
  const timelinePath = "book/_meta/timeline.md";
  writeRel(repoRoot, timelinePath, renderTimeline(idx));
  written.push(timelinePath);

  // Per-project landing pages.
  for (const p of projects) {
    const path = `book/${p}/index.md`;
    writeRel(repoRoot, path, renderProjectIndex(p, {
      chronicles: chroniclesByProject.get(p) ?? [],
      topics: topicsByProject.get(p) ?? [],
      cards: cardsByProject.get(p) ?? [],
    }));
    written.push(path);
  }

  return { written };
}

// ---------------------- renderers ----------------------

function renderFront(args: {
  projects: string[];
  chroniclesByProject: Map<string, ChronicleEntry[]>;
  topicsByProject: Map<string, TopicEntry[]>;
  cardsByProject: Map<string, CardEntry[]>;
  latestUpdate: string;
}): string {
  const totalChronicles = sumMapSizes(args.chroniclesByProject, (c) => !c.skip);
  const totalTopics = sumMapSizes(args.topicsByProject);
  const totalCards = sumMapSizes(args.cardsByProject);

  const lines: string[] = [];
  lines.push("---");
  lines.push("title: 笔记本");
  lines.push(`updated: ${args.latestUpdate}`);
  lines.push("---");
  lines.push("");
  lines.push("# 笔记本");
  lines.push("");
  lines.push(
    `更新于 **${args.latestUpdate}** · ${args.projects.length} 个项目 · ` +
    `${totalChronicles} 篇流水账 · ${totalTopics} 个 topic · ${totalCards} 张卡片`,
  );
  lines.push("");
  lines.push("> Generated by `vibebook publish`. Don't edit by hand — re-runs overwrite.");
  lines.push("");
  lines.push("## 项目");
  lines.push("");
  for (const p of args.projects) {
    const chrs = (args.chroniclesByProject.get(p) ?? []).filter((c) => !c.skip);
    const tops = args.topicsByProject.get(p) ?? [];
    const crds = args.cardsByProject.get(p) ?? [];
    if (chrs.length === 0 && tops.length === 0 && crds.length === 0) continue;
    const lastActive = projectLastActive(chrs, tops, crds);
    lines.push(`### ${p}`);
    lines.push(`最近活跃: ${lastActive}`);
    lines.push("");
    if (chrs.length > 0) {
      lines.push(`**${chrs.length} 篇流水账** — 近三篇:`);
      for (const c of recent(chrs, 3)) {
        lines.push(`  - [${c.title}](${c.path}) — ${c.updatedAt}`);
      }
    }
    if (tops.length > 0) {
      lines.push(`**${tops.length} 个 topic**: ${tops.map((t) => `[${t.topicSlug}](${t.path})`).join(", ")}`);
    }
    if (crds.length > 0) {
      const byType = bucketBy(crds, (c) => c.type);
      const breakdown = [...byType.entries()]
        .sort()
        .map(([type, list]) => `${list.length} ${type}`)
        .join(" / ");
      lines.push(`**${crds.length} 张卡片**: ${breakdown}`);
    }
    lines.push("");
  }
  lines.push("---");
  lines.push("");
  lines.push("- [全局时间线](_meta/timeline.md)");
  lines.push("");
  return lines.join("\n");
}

function renderTimeline(idx: BookIndexV2): string {
  const events: { date: string; ts: string; line: string }[] = [];
  for (const c of Object.values(idx.chronicles)) {
    if (c.skip) continue;
    events.push({
      date: c.updatedAt.slice(0, 10),
      ts: c.updatedAt,
      line: `📝 [${c.title}](../${c.path}) — _${c.project}_ chronicle`,
    });
  }
  for (const t of Object.values(idx.topics)) {
    events.push({
      date: t.updatedAt.slice(0, 10),
      ts: t.updatedAt,
      line: `📚 [${t.topicSlug}](../${t.path}) — _${t.project}_ topic updated`,
    });
  }
  for (const c of Object.values(idx.cards)) {
    events.push({
      date: c.updatedAt.slice(0, 10),
      ts: c.updatedAt,
      line: `💡 [${c.cardSlug}](../${c.path}) — _${c.project}_ ${c.type} card`,
    });
  }
  events.sort((a, b) => (a.ts < b.ts ? 1 : a.ts > b.ts ? -1 : 0));

  const lines: string[] = [];
  lines.push("# 全局时间线");
  lines.push("");
  lines.push("Newest first across every project.");
  lines.push("");
  let lastDate = "";
  for (const e of events) {
    if (e.date !== lastDate) {
      lines.push("");
      lines.push(`## ${e.date}`);
      lines.push("");
      lastDate = e.date;
    }
    lines.push(`- ${e.line}`);
  }
  lines.push("");
  return lines.join("\n");
}

function renderProjectIndex(
  project: string,
  args: { chronicles: ChronicleEntry[]; topics: TopicEntry[]; cards: CardEntry[] },
): string {
  const chrs = args.chronicles.filter((c) => !c.skip);
  const lines: string[] = [];
  lines.push("---");
  lines.push(`title: ${project}`);
  lines.push("---");
  lines.push("");
  lines.push(`# ${project}`);
  lines.push("");
  lines.push(`${chrs.length} 篇流水账 · ${args.topics.length} 个 topic · ${args.cards.length} 张卡片`);
  lines.push("");

  if (args.topics.length > 0) {
    lines.push("## Topics");
    lines.push("");
    for (const t of [...args.topics].sort((a, b) => a.topicSlug.localeCompare(b.topicSlug))) {
      lines.push(`- [${t.topicSlug}](topics/${t.topicSlug}.md) — ${t.contributingThreads.length} threads, updated ${t.updatedAt}`);
    }
    lines.push("");
  }

  if (chrs.length > 0) {
    lines.push("## Chronicles (newest first)");
    lines.push("");
    for (const c of [...chrs].sort((a, b) => (a.updatedAt < b.updatedAt ? 1 : -1))) {
      lines.push(`- [${c.title}](chronicle/${baseName(c.path)}) — ${c.updatedAt}`);
    }
    lines.push("");
  }

  if (args.cards.length > 0) {
    lines.push("## Cards");
    lines.push("");
    const byType = bucketBy(args.cards, (c) => c.type);
    for (const [type, list] of [...byType.entries()].sort()) {
      lines.push(`### ${type}`);
      for (const c of list.sort((a, b) => a.cardSlug.localeCompare(b.cardSlug))) {
        lines.push(`- [${c.cardSlug}](cards/${c.cardSlug}.md)`);
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

// ---------------------- helpers ----------------------

function bucketBy<T, K>(xs: T[], key: (t: T) => K): Map<K, T[]> {
  const m = new Map<K, T[]>();
  for (const x of xs) {
    const k = key(x);
    let arr = m.get(k);
    if (!arr) { arr = []; m.set(k, arr); }
    arr.push(x);
  }
  return m;
}

function sumMapSizes<T>(m: Map<string, T[]>, filter?: (t: T) => boolean): number {
  let total = 0;
  for (const list of m.values()) total += filter ? list.filter(filter).length : list.length;
  return total;
}

function recent(chrs: ChronicleEntry[], n: number): ChronicleEntry[] {
  return [...chrs].sort((a, b) => (a.updatedAt < b.updatedAt ? 1 : -1)).slice(0, n);
}

function projectLastActive(
  chrs: ChronicleEntry[],
  tops: TopicEntry[],
  crds: CardEntry[],
): string {
  const ts: string[] = [];
  for (const c of chrs) ts.push(c.updatedAt);
  for (const t of tops) ts.push(t.updatedAt);
  for (const c of crds) ts.push(c.updatedAt);
  if (ts.length === 0) return "—";
  ts.sort();
  return ts[ts.length - 1].slice(0, 10);
}

function latestUpdate(idx: BookIndexV2): string {
  const ts: string[] = [];
  for (const c of Object.values(idx.chronicles)) ts.push(c.updatedAt);
  for (const t of Object.values(idx.topics)) ts.push(t.updatedAt);
  for (const c of Object.values(idx.cards)) ts.push(c.updatedAt);
  if (ts.length === 0) return "—";
  ts.sort();
  return ts[ts.length - 1].slice(0, 10);
}

function baseName(path: string): string {
  const ix = path.lastIndexOf("/");
  return ix < 0 ? path : path.slice(ix + 1);
}

function writeRel(repoRoot: string, relPath: string, body: string): void {
  const abs = join(repoRoot, relPath);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, body);
}
